definitions:
  enum.DogBreed:
    enum:
    - CHOW
    - HOUND
    type: string
    x-enum-varnames:
    - Chow
    - Hound
  errormodel.BusinessError:
    properties:
      code:
        type: string
      description:
        type: string
    type: object
  request.CustomerPostRequest:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      image_url:
        type: string
      last_name:
        type: string
      updated_at:
        type: string
    type: object
  request.DogPostRequest:
    properties:
      breed:
        allOf:
        - $ref: '#/definitions/enum.DogBreed'
        example: hound
    type: object
  response.CustomerCreateResponse:
    properties:
      customerID:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/customer:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CustomerPostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CustomerCreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errormodel.BusinessError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/errormodel.BusinessError'
      security:
      - ApiKeyAuth: []
      summary: Order credit notation
      tags:
      - Order Management
  /v1/dog/{breed}:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.DogPostRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errormodel.BusinessError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/errormodel.BusinessError'
      security:
      - ApiKeyAuth: []
      summary: Order credit notation
      tags:
      - Order Management
securityDefinitions:
  ApiKeyAuth:
    description: API key
    in: header
    name: X-API-KEY
    type: apiKey
  JWT:
    description: JWT
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
